<a href="https://colab.research.google.com/github/AhmadAlabrash/NLP/blob/main/NLP_Wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import spacy

In [36]:
nlp =spacy.load('en_core_web_sm')

In [37]:
doc = "We just opened our wings, the flying part is coming soon"

In [40]:
def get_txt_without_stopw (doc):
  x=[]
  for word in nlp(doc) :
    if  word.is_stop is False :
      x.append(word.text)
  return  ' '.join(x)

In [41]:
get_txt_without_stopw(doc)

'opened wings , flying coming soon'

In [43]:
import pandas as pd

In [45]:
df =pd.read_json('/content/doj_press.json',lines=True)

In [46]:
df

,id,title,contents,date,topics,components
0,None,Convicted Bomb Plotter Sentenced to 30 Years,"PORTLAND, Oregon. – Mohamed Osman Mohamud, 23,...",2014-10-01T00:00:00-04:00,[],[National Security Division (NSD)]
1,12-919,$1 Million in Restitution Payments Announced t...,WASHINGTON – North Carolina’s Waccamaw River...,2012-07-25T00:00:00-04:00,[],[Environment and Natural Resources Division]
2,11-1002,$1 Million Settlement Reached for Natural Reso...,BOSTON– A $1-million settlement has been...,2011-08-03T00:00:00-04:00,[],[Environment and Natural Resources Division]
3,10-015,10 Las Vegas Men Indicted \r\nfor Falsifying V...,WASHINGTON—A federal grand jury in Las Vegas...,2010-01-08T00:00:00-05:00,[],[Environment and Natural Resources Division]
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division]
...,...,...,...,...,...,...
13082,16-735,Yuengling to Upgrade Environmental Measures to...,The Department of Justice and the U.S. Environ...,2016-06-23T00:00:00-04:00,[Environment],[Environment and Natural Resources Division]
13083,10-473,Zarein Ahmedzay Pleads Guilty to Terror Violat...,The Justice Department announced that Zarein...,2010-04-23T00:00:00-04:00,[],[Office of the Attorney General]
13084,17-045,Zimmer Biomet Holdings Inc. Agrees to Pay $17....,Subsidiary Agrees to Plead Guilty to Violating...,2017-01-12T00:00:00-05:00,[Foreign Corruption],"[Criminal Division, Criminal - Criminal Fraud ..."
13085,17-252,ZTE Corporation Agrees to Plead Guilty and Pay...,ZTE Corporation has agreed to enter a guilty p...,2017-03-07T00:00:00-05:00,"[Asset Forfeiture, Counterintelligence and Exp...","[National Security Division (NSD), USAO - Texa..."
13086,17-304,ZTE Corporation Pleads Guilty for Violating U...,ZTE Corporation pleaded guilty today to conspi...,2017-03-22T00:00:00-04:00,[Counterintelligence and Export Control],"[National Security Division (NSD), USAO - Texa..."

In [47]:
df['content_withoutStop']=df.contents.apply(lambda x: get_txt_without_stopw(x))

In [50]:
df[['contents','content_withoutStop']]

,contents,content_withoutStop
0,"PORTLAND, Oregon. – Mohamed Osman Mohamud, 23,...","PORTLAND , Oregon . – Mohamed Osman Mohamud , ..."
1,WASHINGTON – North Carolina’s Waccamaw River...,WASHINGTON – North Carolina Waccamaw River ...
2,BOSTON– A $1-million settlement has been...,BOSTON – $ 1 - million settlement reach...
3,WASHINGTON—A federal grand jury in Las Vegas...,WASHINGTON — federal grand jury Las Vegas t...
4,"The U.S. Department of Justice, the U.S. Envir...","U.S. Department Justice , U.S. Environmental P..."
...,...,...
13082,The Department of Justice and the U.S. Environ...,Department Justice U.S. Environmental Protecti...
13083,The Justice Department announced that Zarein...,Justice Department announced Zarein Ahmedza...
13084,Subsidiary Agrees to Plead Guilty to Violating...,Subsidiary Agrees Plead Guilty Violating Forei...
13085,ZTE Corporation has agreed to enter a guilty p...,ZTE Corporation agreed enter guilty plea pay $...
13086,ZTE Corporation pleaded guilty today to conspi...,ZTE Corporation pleaded guilty today conspirin...